taco:
    orders:
        pageSize: 10

logging:
    level:
        tacos: DEBUG

---
spring:
    profiles: prod

datasource:
    url: jdbc:mysql://mysql/tacocloud
    username: tutorial
    password: tutorialPS3104

logging:
    level:
        tacos: WARN